# Generated by Django 3.2.7 on 2021-09-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
