# Generated by Django 3.2.7 on 2021-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_phone_number_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='short_intro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_github',
        ),
        migrations.AddField(
            model_name='profile',
            name='chamber_of_commerce_certificate',
            field=models.FileField(blank=True, null=True, upload_to='agency_uploads'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_registartion_certificate',
            field=models.FileField(blank=True, null=True, upload_to='agency_uploads'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cr12',
            field=models.FileField(blank=True, null=True, upload_to='agency_uploads'),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='nea_certificate',
            field=models.FileField(blank=True, null=True, upload_to='agency_uploads'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_years_operations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='physical_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
