# Generated by Django 3.2.7 on 2021-10-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_message_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='union_certificate',
            field=models.FileField(blank=True, null=True, upload_to='agency_uploads'),
        ),
    ]
