# Generated by Django 3.2.7 on 2021-10-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211021_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='education_level',
            field=models.CharField(blank=True, choices=[('High School', 'High School')], max_length=200, null=True),
        ),
    ]
