# Generated by Django 3.2.7 on 2021-10-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_message_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='county',
            field=models.CharField(blank=True, choices=[('Marsabit', 'Marsabit'), ('Trans-Nzoia', 'Trans-Nzoia'), ('Muranga', 'Muranga'), ('Turkana', 'Turkana'), ('Narok', 'Narok'), ('Nyandarua', 'Nyandarua'), ('Lamu', 'Lamu'), ('Kakamega', 'Kakamega'), ('Homa Bay', 'Homa Bay'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('West Pokot', 'West Pokot'), ('Kilifi', 'Kilifi'), ('Garissa', 'Garissa'), ('Nyamira', 'Nyamira'), ('Taita–Taveta', 'Taita–Taveta'), ('Kisii', 'Kisii'), ('Kirinyaga', 'Kirinyaga'), ('Machakos', 'Machakos'), ('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kajiado', 'Kajiado'), ('Kiambu', 'Kiambu'), ('Nakuru', 'Nakuru'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Laikipia', 'Laikipia'), ('Kisumu', 'Kisumu'), ('Makueni', 'Makueni'), ('Uasin Gishu', 'Uasin Gishu'), ('Baringo', 'Baringo'), ('Mandera', 'Mandera'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Nyeri', 'Nyeri'), ('Kericho', 'Kericho'), ('Meru', 'Meru'), ('Nairobi', 'Nairobi'), ('Tana River', 'Tana River'), ('Migori', 'Migori'), ('Wajir', 'Wajir'), ('Isiolo', 'Isiolo'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Busia', 'Busia'), ('Nandi', 'Nandi'), ('Vihiga', 'Vihiga')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='education_level',
            field=models.CharField(blank=True, choices=[('University', 'University'), ('High School', 'High School'), ('College', 'College'), ('Primary School', 'Primary School')], max_length=200, null=True),
        ),
    ]
