# Generated by Django 3.2.7 on 2021-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20211021_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='county',
            field=models.CharField(blank=True, choices=[('Lamu', 'Lamu'), ('Isiolo', 'Isiolo'), ('Kisumu', 'Kisumu'), ('Nandi', 'Nandi'), ('Marsabit', 'Marsabit'), ('Narok', 'Narok'), ('Garissa', 'Garissa'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nyandarua', 'Nyandarua'), ('Trans-Nzoia', 'Trans-Nzoia'), ('Embu', 'Embu'), ('West Pokot', 'West Pokot'), ('Mandera', 'Mandera'), ('Kericho', 'Kericho'), ('Laikipia', 'Laikipia'), ('Nyeri', 'Nyeri'), ('Tana River', 'Tana River'), ('Wajir', 'Wajir'), ('Kitui', 'Kitui'), ('Siaya', 'Siaya'), ('Uasin Gishu', 'Uasin Gishu'), ('Machakos', 'Machakos'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Samburu', 'Samburu'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kirinyaga', 'Kirinyaga'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Migori', 'Migori'), ('Nyamira', 'Nyamira'), ('Nakuru', 'Nakuru'), ('Taita–Taveta', 'Taita–Taveta'), ('Muranga', 'Muranga'), ('Meru', 'Meru'), ('Kilifi', 'Kilifi'), ('Kwale', 'Kwale'), ('Kiambu', 'Kiambu'), ('Baringo', 'Baringo'), ('Vihiga', 'Vihiga'), ('Busia', 'Busia'), ('Kisii', 'Kisii'), ('Mombasa', 'Mombasa'), ('Turkana', 'Turkana'), ('Homa Bay', 'Homa Bay'), ('Makueni', 'Makueni'), ('Nairobi', 'Nairobi')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='education_level',
            field=models.CharField(blank=True, choices=[('University', 'University'), ('Primary School', 'Primary School'), ('College', 'College'), ('High School', 'High School')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='county',
            field=models.CharField(blank=True, choices=[('Lamu', 'Lamu'), ('Isiolo', 'Isiolo'), ('Kisumu', 'Kisumu'), ('Nandi', 'Nandi'), ('Marsabit', 'Marsabit'), ('Narok', 'Narok'), ('Garissa', 'Garissa'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nyandarua', 'Nyandarua'), ('Trans-Nzoia', 'Trans-Nzoia'), ('Embu', 'Embu'), ('West Pokot', 'West Pokot'), ('Mandera', 'Mandera'), ('Kericho', 'Kericho'), ('Laikipia', 'Laikipia'), ('Nyeri', 'Nyeri'), ('Tana River', 'Tana River'), ('Wajir', 'Wajir'), ('Kitui', 'Kitui'), ('Siaya', 'Siaya'), ('Uasin Gishu', 'Uasin Gishu'), ('Machakos', 'Machakos'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Samburu', 'Samburu'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kirinyaga', 'Kirinyaga'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Migori', 'Migori'), ('Nyamira', 'Nyamira'), ('Nakuru', 'Nakuru'), ('Taita–Taveta', 'Taita–Taveta'), ('Muranga', 'Muranga'), ('Meru', 'Meru'), ('Kilifi', 'Kilifi'), ('Kwale', 'Kwale'), ('Kiambu', 'Kiambu'), ('Baringo', 'Baringo'), ('Vihiga', 'Vihiga'), ('Busia', 'Busia'), ('Kisii', 'Kisii'), ('Mombasa', 'Mombasa'), ('Turkana', 'Turkana'), ('Homa Bay', 'Homa Bay'), ('Makueni', 'Makueni'), ('Nairobi', 'Nairobi')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='education_level',
            field=models.CharField(blank=True, choices=[('University', 'University'), ('Primary School', 'Primary School'), ('College', 'College'), ('High School', 'High School')], max_length=200, null=True),
        ),
    ]
