# Generated by Django 3.2.7 on 2021-10-05 08:02

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210929_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
